### ISSUE TITLE
Duplicate unique title ID...

### ISSUE THREAD

**Issue by ksanislo** [Wolvan/encTitleKeys.bin-Updater#1]
You're using a duplicate of a previously used titleid entry by Rinnegatamante's ORGANIZ3D. I'll have to delist your application from the [3DS Homebrew Title Database](https://titledb.com) until this is fixed.

Can you please switch to an unused title ID and resubmit your application to TitleDB.com?

Thanks,
-Ken

**Comment by Wolvan** [comment]
Thanks for bringing this to my attention! I'll push a new release in a moment and then resubmit!

**Comment by Wolvan** [comment]
@ksanislo I think I resubmitted but I am not sure since it's my first time using TitleDB.com.
Did I do it right?

**Comment by ksanislo** [comment]
Sorry about that, I accidentally introduced a bug in the HTTP headers I was passing to github, so I couldn't interact with their API to list the new version. It's fixed now and your new build looks good.

**Comment by Wolvan** [comment]
Thanks! Another question though...
Is titledb going to automatically update when I push a new release on github?

**Comment by ksanislo** [comment]
Yeah, TitleDB checks for updated github releases every 5 minutes, and updates accordingly, you won't need to do anything to keep things current.
