### ISSUE TITLE
Discord link in README is invalid

### ISSUE THREAD

**Issue by favna** [Wolvan/encTitleKeys.bin-Updater#2]
When generating links in discord you have to click `advanced settings` to select "Expire After: Never". The current link has expired.

![image](https://cloud.githubusercontent.com/assets/4019718/16902113/53643610-4c55-11e6-90e6-83e3e6bfb0f9.png)

![image](https://cloud.githubusercontent.com/assets/4019718/16902117/6898da68-4c55-11e6-9f2d-234a5bbde86f.png)

**Comment by Wolvan** [comment]
The link has actually been invalidated by the discord server's owner due to not being OK with having it shared on the github any longer, apologies.
