### ISSUE TITLE
Do you intend to continue this fork?

### ISSUE THREAD

**Issue by ksanislo** [Wolvan/encTitleKeys.bin-Updater#3]
I gave MafMaf a build of the fixed lpp i made the other day for his version of this, so now it can do direct updates instead of needing a separate server. If you don't intend to maintain a full fork, I'd like to delist this version to help reduce confusion for which version people should pick.

What do you think?

-Ken

**Comment by Wolvan** [comment]
I am going to continue this fork, yes. But I might wanna rebrand it anyways, since it does a bit more than just download the encTitleKeys.bin now. How would Titlekeys tools sound?

**Comment by ksanislo** [comment]
As much as I love accuracy in naming, encTitleKeys.bin-updater is a terrible name for anything. Titlekey tools would be much better. The different name and a new icon would definitely help avoid confusing the users as well, so go for it! I've cleared this as a second entry with the old name, but you can change your repo name and resubmit whenever you're ready.

**Comment by Wolvan** [comment]
I probably won't change the repo name since there are a bunch of links pointing here, but I'll change name in Readme and makefile of course. Unfortunately, I am really not the greatest with new icon/banners so if you knew someone that could help me out, that would be very much appreciated

**Comment by ksanislo** [comment]
I'd just grab some random picture of an key and crop it to be an icon. Something kinda unusual like http://www.mbrmarketing.com/media/smlksuprakey.gif

But I'm really bad at graphics myself. Haha

**Comment by Wolvan** [comment]
Rebranded to Titlekeys Tools in 6f6bd2f1ce802f532c079edfe4fead70c0d6d0d9, release pushed soon.

**Comment by Wolvan** [comment]
Could you check the cached icon? It stills shows the old one

**Comment by ksanislo** [comment]
It looks like the [new icon for me](http://api.titledb.com/images/0004000000130800.png) fwiw...

**Comment by Wolvan** [comment]
![image](https://cloud.githubusercontent.com/assets/1437010/16964374/61d4b268-4dfb-11e6-8e33-90a4bd84d0db.png)

**Comment by ksanislo** [comment]
Browser cache perhaps? Hold left shift and click refresh and see if it goes back to normal.

**Comment by Wolvan** [comment]
Works on my firefox which never opened titledb but not on chrome even with cache refresh, weird. Eh, doesn't matter

**Comment by ksanislo** [comment]
Yeah, Chrome's caching can be a bit screwy... and how to fix it differs based on version and what OS you're on. The web server isn't trying to identity the image as old content, it definitely sees the mtime changed on the file, so it must just be bad handling in Chrome...

**Comment by Wolvan** [comment]
Yeah I am sure it's just my chrome cache being screwy. Don't worry about it

**Comment by tatundria** [comment]
It would be great to use the default freeShop icon and banner, including an update symbol in the middle of the icon.

**Comment by Wolvan** [comment]
Would you be able to provide that, @tatundria ?

**Comment by tatundria** [comment]
I would love to... but I have not idea on how to do it...

**Comment by Wolvan** [comment]
That's fine, no worries. There's also the thing that this is no longer really only a tool to update the encTitleKeys.bin but to interact with 3ds.titlekeys.com from your 3ds, so I am not sure if the freeshop icon would be a good fit here

**Comment by ghost** [comment]
"encTitleKeys.bin-updater is a terrible name for anything"

I completely agree. I renamed it to "encTitleKeysUpdater" with 1.1, though. Although I guess that still doesn't sound much better.

Good work on the fork btw, Wolvan. I've used it and I'm glad you kept the "you are a pirate" jingle :p

Also, "Titlekey Tools" is a much better name than "Titlekeys Tools" imo

**Comment by Wolvan** [comment]
Thanks, glad you think so MatMaf. Wouldn't have gotten into 3ds Homebrew if it wasn't for your version of the updater.
And the jingle is top tier, I could never remove that, especially since it is very fitting.

**Comment by ksanislo** [comment]
Damn it, now I'm going to have to go install this just so I can hear the banner jingle. ;)

**Comment by Wolvan** [comment]
You are aware that you can just download the file assets/audio.wav, right?

**Comment by ksanislo** [comment]
Chrome was refusing to let me play or save it on linux, but I was able to pull the repo via git. That's surprisingly funny... lol

**Comment by ghost** [comment]
Don't worry, Wolvan, your version's way better than mine lol. At least I got autorun and a proper direct download before you :P

**Comment by Wolvan** [comment]
Auto download? Nope, added that in v1.3.0 12 days ago. Auto launch? Yeah, that only came today

**Comment by ghost** [comment]
Oh, sorry for the confusion. I meant Boot app -> autodownload -> autolaunch freeShop.

**Comment by Wolvan** [comment]
But Mat, Boot App -> Autodownload IS implemented in v1.3 as a setting

**Comment by ghost** [comment]
well r.i.p. me, congrats
